### ISSUE TITLE
Change "other" options to "self identify" open-ended options

### ISSUE THREAD

**Issue by 0xreid** [drnikki/open-demographics#11]
It's really helpful to gives folks the option to self identify, rather than forcing people into the category of "other" when the other options don't fit. RobotHugs has a great comic that goes in-depth about this and why the option for self identification is important: http://www.robot-hugs.com/other-five/

I'd be happy to open a PR for this, if this makes sense for this project.

**Comment by drnikko** [comment]
@bronwynlewis yes, I'd love a PR (and don't forget to add yourself to the contributors file if you're comfortable doing so).  I do have concerns about how we can help others self-identify and also maintain data validity when there are many choices.

That concern is cart-before-the-horse a bit, however.  I'd like to start from a place of _inclusion_ and make decisions  based on the belief that we can be both inclusive and data-valid. 

Thanks for your thoughts!

**Comment by 0xreid** [comment]
Just opened a PR for this. And yes, totally agree on that approach. Thanks so much for working on this.
