### ISSUE TITLE
Tenure

### ISSUE THREAD

**Issue by emmairwin** [drnikki/open-demographics#19]
The amount of time someone has been a part of a community.  
This helps us with visualization of volunteer life cycles - when do we lose people, is that primarily women and so on.

**Comment by drnikko** [comment]
I think this is so important, though it's not strictly a demographic question.  

I wonder how people will decide how long they've been involved - is it date of first contribution? Age of account (in the Drupal community), first discovery?  

If we can lower the cognitive load people would have answering by providing some guidelines, it would be a quick question to add.

**Comment by emmairwin** [comment]
YOu're right this isn't the right place.

**Comment by drnikko** [comment]
haha that was fast. :)  I don't want it to get lost though... should we start a companion "volunteer data" project in osdiversity?
