### ISSUE TITLE
Primary skillset/function

### ISSUE THREAD

**Issue by emmairwin** [drnikki/open-demographics#20]
I'm not sure this belongs in demographics, but will put here for conversation anyway perhaps.
again thinking of our research around technical and non-technical(l10n, writing etc) contributors. Helpful to be able to get better at enabling success of diverse skillsets

**Comment by drnikko** [comment]
I wonder if a different project / fork might include questions like:
- are you a technical or non-technical contributor
- how long have you been involved
- what barriers have you faced?
etc?

**Comment by drnikko** [comment]
In light of the tightened focus on demographics (as tough and socially-constructed as they are) and the near-term consumption by Drupal.org, I'm closing this issue.
