### ISSUE TITLE
License for materials?

### ISSUE THREAD

**Issue by npch** [drnikki/open-demographics#30]
Would it be useful to clarify the licensing for these materials e.g. are they CC-BY / CC-BY-SA / CC0?

It looks like a really interesting project and we'd be interested in contributing UK perspective on the questions.

**Comment by drnikko** [comment]
@npch I'd love to have your contributions.   Please feel free to open other issues or PRs as you can.

**Comment by emmairwin** [comment]
I think @npch means: https://creativecommons.org/licenses/

**Comment by npch** [comment]
@emmairwin is correct I meaning the most open creative commons licenses..

I'm looking for clarification on how the open demographics materials are licensed for people to use, so that I have an understanding also of how contributions I might make would be available for others.

**Comment by drnikko** [comment]
I'm thinking that `Attribution-ShareAlike CC BY-SA` makes the most sense, but open to discussion.

**Comment by ebarry** [comment]
I heartily agree that `Attribution-ShareAlike CC BY-SA` makes the most sense. :)
Would be open to hearing motions for CC0 though.

**Comment by drnikko** [comment]
Hi, all - just added #41 - a cc-by-sa license.  Would someone give it a +1 and I'll merge?  

Thanks for all of your input!

**Comment by drnikko** [comment]
Thanks to @mradcliffe for the review!
