### ISSUE TITLE
Add website url to repo description

### ISSUE THREAD

**Issue by patcon** [drnikki/open-demographics#35]
Hiya! Just heard about this project from Public Lab's talk a LibrePlanet, and I love it!

Took me awhile to find the website itself, so I wanted to suggest:
- [x] adding it beside the GitHub repo description
- [ ] linking it prominently in the README: https://github.com/drnikki/open-demographics/pull/36

https://drnikki.github.io/open-demographics/

Thanks so much for your consideration!

**Comment by Be-ing** [comment]
Thanks! I had a hard time finding this from a web search and looking at this GitHub repository.

**Comment by patcon** [comment]
No problemo!

bump @drnikki  :)

**Comment by drnikko** [comment]
Oh my gosh, thanks for making this ticket - I didn't know other folks were even talking about it.  

I'll get that done right now!
