### ISSUE TITLE
Code of conduct update

### ISSUE THREAD

**Issue by CoralineAda** [drnikki/open-demographics#39]
It's best for the code of conduct to exist as a standalone document, and it's very important that the document include contact information for reporting a violation as well as the process that the admins will follow to enforce the code. Thanks, and let me know if I can help!

**Comment by drnikko** [comment]
Hi @CoralineAda thank you so much for opening this issue!  I made a pull request here: https://github.com/drnikki/open-demographics/pull/40 that I'd love your review on.

Right now (and for the near-term future), I'm the only admin and will happily block racists, homophobes, bigots and others as I see fit.  I'm not sure if there's a set example for this kind of reporting structure, but happy to rework the language as you recommend.  Appreciate all the work you do. <3

**Comment by drnikko** [comment]
I merged #40.
