### ISSUE TITLE
Location: Can choose not to disclose

### ISSUE THREAD

**Issue by hmitsch** [drnikki/open-demographics#49]
Hi all,

we had a question about the `Dropdown of Countries` described in https://github.com/drnikki/open-demographics/blob/master/doc-source/questions/location.rst .

In a scenario where you want to make the "Location question" mandatory, have you ever discussed how to allow people not to disclose their location in the Country Dropdown? Is it advisable to add a `choose not to state` option?

Best regards,
   Henrik

**Comment by drnikko** [comment]
Hi Henrik,

Thank you for this - Yes, I'd include a "decline to state".  Would be happy to accept a PR to add this specifically.

**Comment by germonprez** [comment]
PR #67 created to address this issue.

**Comment by GeorgLink** [comment]
closed with #67
