### ISSUE TITLE
Review and verify age ranges

### ISSUE THREAD

**Issue by drnikko** [drnikki/open-demographics#5]
Feedback wanted on 
https://github.com/drnikki/open-demographics/blob/master/age.md

**Comment by gerbenjacobs** [comment]
I'd like to see smaller ranges in the early years. I have no extensive knowledge, but I feel such a distinction would be beneficial. I found this research for _pediatric age ranges_ with the accompanying definition by the NICHD.

Stage | Definitions (Release Date July 6, 2011)
-- | --
Preterm neonatal | The period at birth when a newborn is born before the full gestational period
Term neonatal | Birth– 27 d
Infancy | 28 d–12 mo
Toddler | 13 mo–2 y
Early childhood | 2–5 y
Middle childhood | 6–11 y
Early adolescence | 12–18 y
Late adolescence | 19–21 y

See "Table 2" at http://pediatrics.aappublications.org/content/129/Supplement_3/S153 (or as [PDF](http://pediatrics.aappublications.org/content/pediatrics/129/Supplement_3/S153.full.pdf))

**Comment by drnikko** [comment]
@gerbenjacobs thanks for sharing this.  I'm not sure at what age a person can become a contributor to an OSS project, but certainly don't want to exclude or render invisible younger contributors.

Would love to hear other thoughts on this, given that the idea is that individual contributors would be answering these questions.

**Comment by KaiBot3000** [comment]
I have a few thoughts on ages:

- I agree than infants are unlikely to be open-source contributors
- It's nice to capture both "minors" and something close to "college age" (I recognize this is a little US-centered, in that that's a common way we break down ages)
- For writing about the information, it might be nice to have the breakdown close to decades: "80% of our contributors are in their 20's" vs "80% of our contributors are between 25 and 34 years"

How about something like:

### Full Question
    What is your age range?
    () 0-15
    () 15-19
    () 20-24
    () 25-29
    () 30-39
    () 40-49
    () 50-59
    () 60-69
    () 70-79
    () 80+
    () Prefer not to answer

### Short Question
    What is your age range?
    () 0-19
    () 20-35
    () 36-64
    () 65+
    () Prefer not to answer

**Comment by gerbenjacobs** [comment]
Ahh, I was under the impression this was going to be for generic communities as well as open source projects.

In that case such a detailed grouping is probably not needed.

**Comment by drnikko** [comment]
@KaiBot3000 thanks for this breakdown.  For the short question, I think it makes sense to have things break in the same way as in the long question so that it's easier to compare across ranges.  Would you mind opening a PR with that fix in place?

@gerbenjacobs other communities can _absolutely_ use this standard, but the idea is that people will be completing this survey on their own.

**Comment by KaiBot3000** [comment]
@drnikki you're absolutely right about having long and short questions match. I PR'd those notes in #17.
