### ISSUE TITLE
Genderless option appears to be sort of duplicated in gender questions

### ISSUE THREAD

**Issue by NickDickinsonWilde** [drnikki/open-demographics#51]
In /doc-source/questions/gender.rst there is both:
* Agender/genderless
and
* Genderless
options. It seems to me that those should either be 1 entry or the first entry should be *just* Agender. I'd open a PR, but since I have moderate cis cluelessness on the topic figured I'd ask first.

**Comment by drnikko** [comment]
Thanks for opening this @NickWilde1990.  I could see "Agender" being shortened and Genderless being another entry.  Happy to accept a PR on this. <3
