### ISSUE TITLE
open-demographics.com is dead

### ISSUE THREAD

**Issue by bradjones1** [drnikki/open-demographics#71]
Looks like the domain expired.

**Comment by germonprez** [comment]
That's too bad. I'm not sure who runs/pays for the webpage. @drnikki could you help out here?

**Comment by drnikko** [comment]
HI!  It is indeed me - thanks for the reminder to renew the domain subscription.  open-demographics.com is configured in githubpages to redirect to nikkistevens.com/open-demographics.  Happy for it to be a custom gh-pages site, I just didn't want to fuss with hosting in a rush on my last work day of the week. :)

**Comment by GeorgLink** [comment]
Thanks for fixing the domain issue so quickly!
