### ISSUE TITLE
Recommendation: Rename master branch to main

### ISSUE THREAD

**Issue by lee0c** [drnikki/open-demographics#73]
As part of larger efforts to remove harmful terminology from tech's day-to-day, the default branch name in new GitHub repositories is now `main` and this change is echoed in many repositories at many levels of use and visibility. Recommend aligning with this change.

[Guidance on changing default branch name](https://github.com/github/renaming)

[More on the reasoning for this change](https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main)

**Comment by germonprez** [comment]
+1 @lee0c - @drnikki could you make this change as org owner? Thanks so much for this.

**Comment by drnikko** [comment]
Note here with the steps to update everyone's local clone:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

I just made a trivial commit to main (f3c1768) to get github pages to republish.

**Comment by drnikko** [comment]
I waited a bit and it seems like everything is up, so I'm going to close this.  Please reopen if something goes wrong.

And thanks for opening it in the first place!!  This is a super good and important change!
